#+TITLE: 如何在Linux机器之间复制SELinux策略
#+URL: http://linuxtechlab.com/replicate-selinux-policies-among-linux-machines/
#+AUTHOR: lujun9972
#+TAGS: system SELinux
#+DATE: [2017-11-06 一 16:56]
#+LANGUAGE:  zh-CN
#+OPTIONS:  H:6 num:nil toc:t \n:nil ::t |:t ^:nil -:nil f:t *:t <:nil



SELinux 或者说 Security Enhaced Linux, 是一套运行在用户空间下的内核修改工具, 它是一种名为MAC(Mandatory access controls)的访问策略的具体实现. 
它约束了服务的特权,因此能够消除由于未检查特权导致的问题.

SELinux中并没有root用户和超级用户的概念,由于不依赖于setuid/setgid，因此没有Linux安全机制的那些缺陷. 
我在文章 [[http://linuxtechlab.com/beginners-guide-to-selinux/][Beginner’s guide to SELinux]] 中有介绍过SELinux. 想深入了解SELinux的话可以查看那篇文章.

本文中, 我们会讨论一下如何将一个系统中的SELinux策略复制到另一个系统. 不过在此之前，让我们还有一些事要做,

(Also Read:[[http://linuxtechlab.com/linux-disk-cloning-using-dd-cat-commands/][Cloning Disks using dd & cat commands for Linux systems)]]

* 先决条件

为了复制SELinux策略, 我们需要 ‘semange’ 命令. 在CentOS系统中运行以下命令以确定 ‘semange’ 是否已安装.
#+BEGIN_SRC shell
  $ semanage –help
#+END_SRC

若出现下面错误，则表示尚未安装,

#+BEGIN_EXAMPLE
  -bash: semanage: command not found
#+END_EXAMPLE

安装 ‘semanage’ 命令需要安装下面package,

#+BEGIN_SRC shell
  $ sudo yum install policycoreutils-python
#+END_SRC

该命令就会安装 ‘semange’ 命令及其依赖.

* 复制SELinux策略

首先将SELinux的所有配置存入文件中,

#+BEGIN_SRC shell
  $ sudo semanage -o /root/local.selinux
#+END_SRC

然后将该文件传送到要复制SELinux策略的机器上

#+BEGIN_SRC shell
  $ scp -rv /root/local.selinux root@192.168.1.100:/root
#+END_SRC

然后就需要恢复该文件了. 为此我们需要ssh到第二台机器上,

#+BEGIN_SRC shell
  $ ssh root@192.168.1.100
#+END_SRC

然后运行下面命令恢复,

#+BEGIN_SRC shell
  # semanage -i /root/local.selinux
#+END_SRC

行了, 这就将第一台机器上的SELinux策略恢复到第二台机器上了.

注意:- 本文适用于CentOS6, 但CentOS5无法将SELinux配置导出到文件中.

另外，我们也需要确定目标机器上的SELinux版本不能低于源机器上的版本，因为 SELinux并不具有向后兼容性.
