#+TITLE: 如何在Linux命令行控制媒体播放器
#+URL: https://www.ostechnix.com/control-media-players-commandline-linux/
#+AUTHOR: lujun9972
#+TAGS: commandline media
#+DATE: [2017-11-08 三 20:27]
#+LANGUAGE:  zh-CN
#+OPTIONS:  H:6 num:nil toc:t \n:nil ::t |:t ^:nil -:nil f:t *:t <:nil


各位音乐爱好者们! 进他我学到一样新东西,那就是在类Unix系统下的命令行控制媒体播放器.
你可以播放,暂停,在播放和暂停间切换, 调高/调低音量, 切上一首/下一首媒体文件, 停止媒体播放等动作.
所偶这些都在终端内完成! 很酷吧? 本文将告诉你两个这样的工具.

* 1. Playerctl

=Playerctl= 是一个在终端制媒体播放的命令行工具. 你可以用它播放,暂停,在播放和暂停间切换, 调高/调低音量, 切上一首/下一首媒体文件, 停止媒体播放等.
通过 Playerctl, 我们可以管理任何实现了 [[http://specifications.freedesktop.org/mpris-spec/latest/][MPRIS]] D-Bus 接口规范的媒体播放器. 下面是一些常见的能被 Playerctl 管理的播放器:

+ Audacious,
+ Bmp,
+ Spotify,
+ Mplayer/SMplayer,
+ VLC,
+ Xmms2.

** 安装

Playerctl 存在于所有现代Linux发行版的官方仓库中. 你可以使用发行版的默认包管理器来安装它.

Arch Linux 上:

#+BEGIN_SRC shell
  sudo pacman -S playerctl
#+END_SRC

Debian, Ubuntu 及其衍生版上:

#+BEGIN_SRC shell
  sudo apt-get install playerctl
#+END_SRC

Fedora 上:

#+BEGIN_SRC shell
  sudo dnf install playerctl
#+END_SRC

openSUSE 上:

#+BEGIN_SRC shell
  sudo zypper install playerctl
#+END_SRC

如果你在官方仓库中找不到, 还可以通过源代码来手工编译和安装. 最新的源代码可以在 [[https://github.com/acrisci/playerctl/releases][发布页面]] 上找到.

** 用法

首先, 使用下面命令列出所有可以控制的播放器(译注:必须是正在运行的播放器):

#+BEGIN_SRC shell
  playerctl -l
#+END_SRC

或者,

#+BEGIN_SRC shell
  playerctl --list-all
#+END_SRC

输出:

#+BEGIN_EXAMPLE
  vlc
  smplayer
#+END_EXAMPLE

你可以查看指定播放器的状态:

#+BEGIN_SRC shell
  $ playerctl status vlc
  Stopped

  $ playerctl status smplayer
  Playing
#+END_SRC

如你所见, 当前有两个可以控制的播放器. Vlc 处于停止状态, smplayer 处于播放状态.

用下面命令来进行播放:

#+BEGIN_SRC shell
  playerctl play -p smplayer
#+END_SRC

或者,

#+BEGIN_SRC shell
  playerctl play --player smplayer
#+END_SRC

在只运行了一个播放器则无需使用 “-p” 或 “–player” 来指定播放器. Playerctl 会自动选择这个播放器来播放.

要暂停播放(假设你只运行了一个播放器), 则运行:

#+BEGIN_SRC shell
  playerctl pause smplayer
#+END_SRC

播放下一首:

#+BEGIN_SRC shell
  playerctl next smplayer
#+END_SRC

播放上一首:

#+BEGIN_SRC shell
  playerctl previous smplayer
#+END_SRC

切换播放与暂停:

#+BEGIN_SRC shell
  playerctl play-pause smplayer
#+END_SRC

若播放器处于暂停状态则会继续播放，若播放器处于播放状态则会暂停播放.

停止播放:

#+BEGIN_SRC shell
  playerctl stop smplayer
#+END_SRC

查看帮助:

#+BEGIN_SRC shell
  $ playerctl --help
  Usage:
  playerctl [OPTION…] COMMAND - Controller for MPRIS players
  For true players only: spotify, vlc, audacious, bmp, xmms2, and others.

  Help Options:
  -h, --help Show help options

  Application Options:
  -p, --player=NAME The name of the player to control (default: the first available player)
  -l, --list-all List the names of running players that can be controlled
  -V, --version Print version information and exit

  Available Commands:
  play Command the player to play
  pause Command the player to pause
  play-pause Command the player to toggle between play/pause
  stop Command the player to stop
  next Command the player to skip to the next track
  previous Command the player to skip to the previous track
  position [OFFSET][+/-] Command the player to go to the position or seek forward/backward OFFSET in seconds
  volume [LEVEL][+/-] Print or set the volume to LEVEL from 0.0 to 1.0
  status Get the play status of the player
  metadata [KEY] Print metadata information for the current track. Print only value of KEY if passed
#+END_SRC


可以去项目的Github页面了解更多信息, 地址列在后面.

* 2. OmniPause

=OmniPause= 是一个python写的通过DBus来控制多媒体播放器的应用程序. 相比 Playerctl, OmniPause 出现的比较晚，尚处于早期的开发阶段. 
不过它的功能很全面，能做到跟 Playerctl 一样的事情.

** 安装

OmniPause 是由 Python 编写的, 因此你需要安装先安装以下依赖. 这些包在所有的Linux发行版的官方仓库上都有, 完全可以用默认的包管理器来安装. So, you can install them using the default package manager.

+ python2
+ dbus-python

之后，克隆该项目:

#+BEGIN_SRC shell
  git clone https://github.com/mel00010/OmniPause.git
#+END_SRC

进入项目目录:

#+BEGIN_SRC shell
  cd OmniPause/
#+END_SRC

运行下面命令安装之.

#+BEGIN_SRC shell
  sudo make install
#+END_SRC

上面命令会拷贝 omnipause.py 程序到 =/usr/local/bin/omnipause= 中.

** 用法

使用方法与 Playerctl 一样. 不过功能稍弱. 只支持以下几个功能:

+ play,
+ pause,
+ next,
+ previous,
+ toggle,
+ stop.

暂停所有正在运行的媒体播放器:

#+BEGIN_SRC shell
  omnipause pause
#+END_SRC

重启被暂停的媒体播放器:

#+BEGIN_SRC shell
  omnipause play
#+END_SRC

停止所有的播放器:

#+BEGIN_SRC shell
  omnipause stop
#+END_SRC

所有正在播放的媒体播放器播放下一首:

#+BEGIN_SRC shell
  omnipause next
#+END_SRC

所有正在播放的播放器播放上一首:

#+BEGIN_SRC shell
  omnipause previous
#+END_SRC

切换所有正在运行播放器的状态:

#+BEGIN_SRC shell
  omnipause toggle
#+END_SRC

如你所见, 你可以使用一个命令控制所有正在运行的媒体播放器. 很简单吧. 不过与 Playerctl 不同, 它没有选项停止指定的播放器，也没有调大/调小音量的功能. 
如果你需要这些功能，还是使用 playerctl 程序吧.

* 相关资源:

+ [[https://github.com/acrisci/playerctl][Playerctl GitHub page]]
+ [[https://github.com/mel00010/OmniPause][OmniPause GitHub page]]
