#+TITLE: 如何设置Linux版的远程桌面连接
#+URL: https://www.linux.com/learn/intro-to-linux/2017/11/how-set-easy-remote-desktop-access-linux
#+AUTHOR: lujun9972
#+TAGS: Remote Desktop
#+DATE: [2017-11-13 一 12:43]
#+LANGUAGE:  zh-CN
#+OPTIONS:  H:6 num:nil toc:t \n:nil ::t |:t ^:nil -:nil f:t *:t <:nil


Linux是一个非常灵活的操作系统. 它提供了多种方法来完成一个任务. 比如当你需要在本机显示远程桌面时,你可以通过RDP, VNC, SSH, 还有很多第三方的解决方案来完成.
一般来说, 你的桌面系统决定了你会采取的方案, 不过有一些方案确实要好的多. 
一旦你理解了现代的桌面系统为此做了多少优化, 你会发现远程管理Linux桌面系统和带GUI的服务器其实十分简单.

刚才我说过, 你要如何远程桌面取决于你用的是哪个Linux发行版. 本文我将会讲解如何在 在Ubuntu Desktop 18.04 上登陆 Fedora 26的远程桌面,以及如何在Fedora 26 上登陆 Kubuntu的共享远程桌面.
有一个大问题就是，有些桌面系统对该技术支持不够好. 比如, =Wayland= 就不支持 VNC. =Elementary OS 桌面系统= 也是一样. 
因此，我这里只会演示在Ubuntu 18.04如何连接到 Fedora 26,以及如何从 Fedora 26 上连接到 Kubuntu 17.10.
我会用到的工具包括 =remmina=, =krfb=, 以及 =GNOME= 内建的一些工具.

* 从 Ubuntu 连接到 Fedora

Fedora 26的最终发行版, 默认使用的是 GNOME 桌面系统, 其设置远程连接的方法十分直接(因为所有东西都默认安装好了).
你要做的第一件事就是启用 =sharing= 功能. 打开 =GNOME Dash= 然后输入 =sharing=, 就会看到有个 =Sharing= 选项, 点击就能打开这个工具. 
在打开的窗口中将开关点到ON的位置,然后点击 =Screen Sharing=. 在打开的窗口中(图 1), 选中 =Allow connections to control the screen=.

[[https://www.linux.com/files/images/sharing1jpg]]

图 1: Enable Sharing in Fedora 26.
[[https://www.linux.com/licenses/category/used-permission][Used with permission]]

你也可以选中 =access options= 中的 =New connections must ask for access and requiring a password=. 
我十分推荐选上该选项,选上它对你几乎没有影响. 而之后, 当有人想连接上你的远程桌面时，只有认证后才能建立连接.
然后关闭窗口.

初始条件下, Fedora防火墙开放了所需的端口, 远程链接直接就能用了. 如果有问题，请回到 =GNOME Dash= 然后输入 =firewall=.
就会出现一个防火墙图标, 点击它, 然后输入管理员密码. 在弹出的窗口中点击 =Services= 然后向下滚动直到看见 =vnc-server= 为止 (图 2).

[[https://www.linux.com/files/images/sharing2jpg]]

图 2: Enabling the necessary VNC ports through the firewall.
[[https://www.linux.com/licenses/category/used-permission][Used with permission]]

点击启用 =vnc-server= 然后再次输入管理员密码. 现在允许连接 VNC 端口了.

下面来到 Ubuntu 机器. 我们需要安装 =remmina= 应用(这是一款不错的远程客户端应用).
由于标准仓库中的版本有一些bug, 我们可以通过以下步骤安装最新版的应用:

1. 使用命令 =sudo apt-add-repository ppa:remmina-ppa-team/remmina-next= 添加仓库
   
2. 使用命令 =sudo apt update= 更新apt源
   
3. 使用命令 =sudo apt-get install remmina remmina-plugin-rdp remmina-plugin-gnome libfreerdp-plugins-standard= 安装软件
   
在桌面菜单输入 =remmina= 就能打新安装的软件了. 在地址窗口中(图 3), 从下拉框中选择 =VNC=, 输入Fedora机器的IP地址,然后按下回车.

[[https://www.linux.com/files/images/sharing3jpg]]

图 3: The remmina main window.
[[https://www.linux.com/licenses/category/used-permission][Used with permission]]

按下回车后, Fedora 桌面系统就会弹出通知. 点击 =Accept= 后(图 4)就会创建链接,Ubuntu机器上的人就可以控制你的fedora桌面了.

[[https://www.linux.com/files/images/sharing4jpg]]

图 4: Accepting a request to share out the desktop on Fedora 26.
[[https://www.linux.com/licenses/category/used-permission][Used with permission]]

* 从 Fedora 连接 Kubuntu

现在让我们试试从 Fedora 连接到 Kubuntu. 这里我们还是使用remmina作为客户端, 因此我们先要在 Fedora 上安装remmina.
打开终端并输入命令 =sudo dnf install remmina= 安装即可.

安装好remmina后, 就的在 Kubuntu 桌面系统上安装必须的软件了. 这个要安装的软件就是 =krfb=,使用命令 =sudo apt install krfb= 来安装.
安装好krfb后, 就能在 =KDE= 菜单中输入 =krfb=. 点击筛选出的结果后在打开的窗口中选中 =Enable Desktop Sharing= (图 5).

[[https://www.linux.com/files/images/sharing5jpg]]

图 5: Enabling desktop sharing on Kubuntu, via krfb.
[[https://www.linux.com/licenses/category/used-permission][Used with permission]]

=krfb= 还会告诉你客户端连接的IP地址和登陆密码. 如果你不喜欢这个密码，也可以点击更改按钮更改该密码.

到了这一步, 你的 KDE 桌面已经可以与他人共享了. 回到 Fedora 机器, 打开 GNOME Dash, 输入 remmina 并点击图标打开.
在下拉框中选择 =VNC=, 输入 Kubuntu 机器上的IP地址然后按下回车. krfb会提示你输入密码. 输入krfb的密码后点击 =OK=.
在 Kubuntu 桌面上会提示是否接受该连接. 接受后, Fedora 上就会显示出 Kubuntu 桌面来了. 你可以做事了.

* Simple remote desktop connection

当然, 除此之外还有很多其他途径可以创建链接(而且有些桌面系统可能会要比这里说的复杂一些).
好在现代Linux的桌面发布版都包含了创建远程连接的所有必须的东西，这使得创建远程连接变得前所未有的简单.
如果你所选择的桌面系统并没有文中的这些工具, 你也可以从众多的 VNC 服务端中挑选其他的替代品(比如[[https://wiki.gnome.org/Projects/Vino][vino]], [[http://tigervnc.org/][TigerVNC]], 和 [[https://www.tightvnc.com/][tightvnc]]).
使用这些标准的 VNC 服务用起来可能没那么易用，但是一旦配置完成，也是同样可靠的.
